# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-12 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
